
version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQLDATA: /data/mysql
    volumes:
      - ./.docker/mysql:/data/mysql
    ports:
      - "3308:3306"
    restart: unless-stopped
    networks:
      - mysql
networks:
  mysql:
    driver: bridge